import { IFacilityMock } from './facility.interface';
import { FACILITY_VARIANT } from './facility.variant';

/**
 *  This is just a Mock Interface for the Facility Component
 *  It has to be deleted once the actual implementation is done
 * */
export const facilities: IFacilityMock[] = [
	{
		id: '1',
		icon: 'battery-empty',
		notification: '99+',
		heading: 'totally legal waste disposal',
		subheading: 'No shady business.com',
		variant: FACILITY_VARIANT.SUCCESS,
		pumps: 99,
		location: 'Ethical Valley',
	},
	{
		id: '2',
		icon: 'water-fish',
		notification: '3',
		heading: 'Water Tank - FAU Erlangen',
		subheading: 'Large Aquarium in CS Department building',
		variant: FACILITY_VARIANT.CRITICAL,
		pumps: 38,
		location: 'Erlangen',
	},
	{
		id: '3',
		icon: 'water-plant',
		notification: '20',
		heading: 'Water Tank - TU Berlin',
		subheading: 'Submarine testing facility',
		variant: FACILITY_VARIANT.WARNING,
		pumps: 14,
		location: 'Berlin',
	},
	{
		id: '4',
		icon: 'truck',
		notification: '3',
		heading: 'Water Tank - Waste Water Processing',
		subheading: 'Waste water processing in Mosville',
		variant: FACILITY_VARIANT.SUCCESS,
		pumps: 93,
		location: 'Mosville',
	},
    {
        id: '5',
        icon: 'water-plant',
        notification: '2',
        heading: 'H2-Whoa Facility',
        subheading: 'Hydrating the humor in Walla Walla',
        variant: FACILITY_VARIANT.SUCCESS,
        pumps: 47,
        location: 'Walla Walla, WA',
    },
    {
        id: '6',
        icon: 'water-fish',
        notification: '5',
        heading: 'Gush & Flush',
        subheading: 'Overflow management in Truth or Consequences',
        variant: FACILITY_VARIANT.SUCCESS,
        pumps: 65,
        location: 'Truth or Consequences, NM',
    },
    {
        id: '7',
        icon: 'water-fish',
        notification: '1',
        heading: 'Splash & Dash Depot',
        subheading: 'Quick water refills in Poughkeepsie',
        variant: FACILITY_VARIANT.SUCCESS,
        pumps: 80,
        location: 'Poughkeepsie, NY',
    },
    {
        id: '8',
        icon: 'water-fish',
        notification: '0',
        heading: 'Dribble & Drizzle Station',
        subheading: 'Light waterworks in Kalamazoo',
        variant: FACILITY_VARIANT.SUCCESS,
        pumps: 12,
        location: 'Kalamazoo, MI',
    },
    {
        id: '9',
        icon: 'water-fish',
        notification: '4',
        heading: 'Sprinkle & Tinkle',
        subheading: 'Emergency hydration in Intercourse',
        variant: FACILITY_VARIANT.SUCCESS,
        pumps: 34,
        location: 'Intercourse, PA',
    },
    {
        id: '10',
        icon: 'water-fish',
        notification: '3',
        heading: 'Fountain Follies',
        subheading: 'Water amusement in Dingle',
        variant: FACILITY_VARIANT.SUCCESS,
        pumps: 55,
        location: 'Dingle, Ireland',
    },
    {
        id: '11',
        icon: 'water-fish',
        notification: '2',
        heading: 'Wet & Wild',
        subheading: 'Aquatic adventures in Boring',
        variant: FACILITY_VARIANT.SUCCESS,
        pumps: 23,
        location: 'Boring, OR',
    },
    {
        id: '12',
        icon: 'water-fish',
        notification: '7',
        heading: 'Geyser Guys',
        subheading: 'Hot springs handling in Bath',
        variant: FACILITY_VARIANT.SUCCESS,
        pumps: 45,
        location: 'Bath, UK',
    },
    {
        id: '13',
        icon: 'water-fish',
        notification: '1',
        heading: 'Well, Well, Well',
        subheading: 'Deep water retrieval in Waterford',
        variant: FACILITY_VARIANT.SUCCESS,
        pumps: 38,
        location: 'Waterford, Ireland',
    },
    {
        id: '14',
        icon: 'water-fish',
        notification: '6',
        heading: 'Niagara Nitwits',
        subheading: 'Falls fun in Niagara Falls',
        variant: FACILITY_VARIANT.SUCCESS,
        pumps: 99,
        location: 'Niagara Falls, NY',
    },
    {
        id: '15',
        icon: 'water-fish',
        notification: '3',
        heading: 'Hydrant Hijinks',
        subheading: 'Street waterworks in Hot Coffee',
        variant: FACILITY_VARIANT.SUCCESS,
        pumps: 76,
        location: 'Hot Coffee, MS',
    },
    {
        id: '16',
        icon: 'water-fish',
        notification: '2',
        heading: 'Drop Zone',
        subheading: 'Water delivery in Last Chance',
        variant: FACILITY_VARIANT.SUCCESS,
        pumps: 40,
        location: 'Last Chance, CO',
    },
    {
        id: '17',
        icon: 'water-fish',
        notification: '4',
        heading: 'Filter Funnies',
        subheading: 'Clean water fun in Odd',
        variant: FACILITY_VARIANT.SUCCESS,
        pumps: 67,
        location: 'Odd, WV',
    },
    {
        id: '18',
        icon: 'water-fish',
        notification: '1',
        heading: 'River Rascals',
        subheading: 'River water treatment in Funk',
        variant: FACILITY_VARIANT.SUCCESS,
        pumps: 82,
        location: 'Funk, NE',
    },
    {
        id: '19',
        icon: 'water-fish',
        notification: '5',
        heading: 'Tank Terrors',
        subheading: "Reservoir management in Monkey's Eyebrow",
        variant: FACILITY_VARIANT.SUCCESS,
        pumps: 51,
        location: "Monkey's Eyebrow, KY",
    },
    {
        id: '20',
        icon: 'water-fish',
        notification: '0',
        heading: 'Bucket Brigade',
        subheading: 'Emergency water supply in Truthville',
        variant: FACILITY_VARIANT.SUCCESS,
        pumps: 33,
        location: 'Truthville, NY',
    },
];
