name: Lint Test Build

on:
    push:
        branches:
            - develop
    pull_request:
        branches:
            - develop
    workflow_dispatch:

jobs:
    install-deps:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v3
              with:
                  version: 8

            - name: Restore cached npm dependencies
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}

            - uses: actions/setup-node@v4
              if: steps.cache.outputs.cache-hit != 'true'
              with:
                  node-version: 20.x

            - run: pnpm install --frozen-lockfile
              if: steps.cache.outputs.cache-hit != 'true'

            - name: Generate prisma client
              run: pnpm prisma generate

    lint:
        runs-on: ubuntu-latest
        needs: install-deps
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - uses: pnpm/action-setup@v3
              with:
                  version: 8

            - run: git fetch --no-tags --prune --depth=1 origin develop

            - name: Cache node modules
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}

            - run: pnpm nx affected --target=lint --parallel=3 --configuration=ci --base=origin/develop

    test:
        runs-on: ubuntu-latest
        needs: install-deps
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - uses: pnpm/action-setup@v3
              with:
                  version: 8

            - run: git fetch --no-tags --prune --depth=1 origin develop

            - name: Cache node modules
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}

            - run: pnpm nx affected --target=test --parallel=3 --configuration=ci --base=origin/develop

    build:
        runs-on: ubuntu-latest
        needs: install-deps
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - uses: pnpm/action-setup@v3
              with:
                  version: 8

            - run: git fetch --no-tags --prune --depth=1 origin develop

            - name: Cache node modules
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}

            - run: pnpm nx affected --target=build --parallel=3 --configuration=ci --base=origin/develop
